apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  couchdb-user: {{ .Values.couchdb.credentials.username | quote }}
  couchdb-password: {{ .Values.couchdb.credentials.password | quote }}
  couchdb-secret: {{ .Values.couchdb.credentials.secret | quote }}
  postgres-user: {{ .Values.postgresql.credentials.username | quote }}
  postgres-password: {{ .Values.postgresql.credentials.password | quote }}
  postgres-db: {{ .Values.postgresql.credentials.database | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openhim-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  openhim-username: "root@openhim.org"
  openhim-password: "openhim-password"
  openhim-client-password: "interop-password"
  openhim-user-password: "interop-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: mediator-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  openhim-username: {{ .Values.mediator.credentials.openhimUsername | quote }}
  openhim-password: {{ .Values.mediator.credentials.openhimPassword | quote }}
  fhir-username: {{ .Values.mediator.credentials.fhirUsername | quote }}
  fhir-password: {{ .Values.mediator.credentials.fhirPassword | quote }}
  cht-username: {{ .Values.mediator.credentials.chtUsername | quote }}
  cht-password: {{ .Values.mediator.credentials.chtPassword | quote }}
  openimis-username: "Admin"
  openimis-password: "admin123"
