global:
  namespace: <namespace> # Override namespace

createNamespace: false

persistence:
  storageClass: <storageclass> # Override storage

configurator:
  image: 720541322708.dkr.ecr.eu-west-2.amazonaws.com/cht-interop/configurator:latest
  imagePullPolicy: Always # Override pull policy

mediator:
  image: 720541322708.dkr.ecr.eu-west-2.amazonaws.com/cht-interop/mediator:latest
  imagePullPolicy: Always

service:
  type: ClusterIP # Override service type

ingress:
  annotations:
    groupname: "dev-cht-alb"
    tags: "Environment=dev,Team=QA"
    certificate: "arn:aws:iam::720541322708:server-certificate/2025-q4-wildcard-dev-medicmobile-org-letsencrypt"
  # Ensure the host is not already taken. Valid characters for a subdomain are:
  #   a-z, 0-9, and - (but not as first or last character).
  chtHost: "cht-interop.dev.medicmobile.org" # e.g. "mrjones.dev.medicmobile.org"
  openhimConsoleHost: "openhim-cht-interop.dev.medicmobile.org"
  openhimCoreHost: "openhim-api-cht-interop.dev.medicmobile.org"
  openhimRouterHost: "openhim-router-cht-interop.dev.medicmobile.org"
  hosted_zone_id: "Z3304WUAJTCM7P"
  load_balancer: "dualstack.k8s-devchtalb-3eb0781cbb-694321496.eu-west-2.elb.amazonaws.com"

cluster_type: "eks"

resources:
  requests:
    memory: "512Mi" # Override resources
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
