apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: health-interop
type: Opaque
stringData:
  couchdb-user: "admin"
  couchdb-password: "password"
  couchdb-secret: "secret"
  postgres-user: "admin"
  postgres-password: "instant101"
  postgres-db: "hapi"
---
apiVersion: v1
kind: Secret
metadata:
  name: openhim-credentials
  namespace: health-interop
type: Opaque
stringData:
  openhim-username: "root@openhim.org"
  openhim-password: "openhim-password"
  openhim-client-password: "interop-password"
  openhim-user-password: "interop-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: mediator-credentials
  namespace: health-interop
type: Opaque
stringData:
  openhim-username: "interop@openhim.org"
  openhim-password: "interop-password"
  fhir-username: "interop-client"
  fhir-password: "interop-password"
  cht-username: "admin"
  cht-password: "password"
  openimis-username: "Admin"
  openimis-password: "admin123"
